package com.xxpt.dao;

import com.xxpt.bean.Pdf;
import com.xxpt.bean.PdfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    long countByExample(PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int deleteByExample(PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int deleteByPrimaryKey(Integer pdfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int insert(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int insertSelective(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    List<Pdf> selectByExample(PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    Pdf selectByPrimaryKey(Integer pdfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") Pdf record, @Param("example") PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int updateByExample(@Param("record") Pdf record, @Param("example") PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int updateByPrimaryKeySelective(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    int updateByPrimaryKey(Pdf record);
}