package com.xxpt.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnswerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public AnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAIdIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(Integer value) {
            addCriterion("a_id =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(Integer value) {
            addCriterion("a_id <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(Integer value) {
            addCriterion("a_id >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_id >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(Integer value) {
            addCriterion("a_id <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(Integer value) {
            addCriterion("a_id <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<Integer> values) {
            addCriterion("a_id in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<Integer> values) {
            addCriterion("a_id not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(Integer value1, Integer value2) {
            addCriterion("a_id between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a_id not between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAContentIsNull() {
            addCriterion("a_content is null");
            return (Criteria) this;
        }

        public Criteria andAContentIsNotNull() {
            addCriterion("a_content is not null");
            return (Criteria) this;
        }

        public Criteria andAContentEqualTo(String value) {
            addCriterion("a_content =", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotEqualTo(String value) {
            addCriterion("a_content <>", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentGreaterThan(String value) {
            addCriterion("a_content >", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentGreaterThanOrEqualTo(String value) {
            addCriterion("a_content >=", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentLessThan(String value) {
            addCriterion("a_content <", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentLessThanOrEqualTo(String value) {
            addCriterion("a_content <=", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentLike(String value) {
            addCriterion("a_content like", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotLike(String value) {
            addCriterion("a_content not like", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentIn(List<String> values) {
            addCriterion("a_content in", values, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotIn(List<String> values) {
            addCriterion("a_content not in", values, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentBetween(String value1, String value2) {
            addCriterion("a_content between", value1, value2, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotBetween(String value1, String value2) {
            addCriterion("a_content not between", value1, value2, "aContent");
            return (Criteria) this;
        }

        public Criteria andAAnuthorIsNull() {
            addCriterion("a_anuthor is null");
            return (Criteria) this;
        }

        public Criteria andAAnuthorIsNotNull() {
            addCriterion("a_anuthor is not null");
            return (Criteria) this;
        }

        public Criteria andAAnuthorEqualTo(String value) {
            addCriterion("a_anuthor =", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorNotEqualTo(String value) {
            addCriterion("a_anuthor <>", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorGreaterThan(String value) {
            addCriterion("a_anuthor >", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorGreaterThanOrEqualTo(String value) {
            addCriterion("a_anuthor >=", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorLessThan(String value) {
            addCriterion("a_anuthor <", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorLessThanOrEqualTo(String value) {
            addCriterion("a_anuthor <=", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorLike(String value) {
            addCriterion("a_anuthor like", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorNotLike(String value) {
            addCriterion("a_anuthor not like", value, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorIn(List<String> values) {
            addCriterion("a_anuthor in", values, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorNotIn(List<String> values) {
            addCriterion("a_anuthor not in", values, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorBetween(String value1, String value2) {
            addCriterion("a_anuthor between", value1, value2, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAAnuthorNotBetween(String value1, String value2) {
            addCriterion("a_anuthor not between", value1, value2, "aAnuthor");
            return (Criteria) this;
        }

        public Criteria andAQidIsNull() {
            addCriterion("a_qid is null");
            return (Criteria) this;
        }

        public Criteria andAQidIsNotNull() {
            addCriterion("a_qid is not null");
            return (Criteria) this;
        }

        public Criteria andAQidEqualTo(Integer value) {
            addCriterion("a_qid =", value, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidNotEqualTo(Integer value) {
            addCriterion("a_qid <>", value, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidGreaterThan(Integer value) {
            addCriterion("a_qid >", value, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_qid >=", value, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidLessThan(Integer value) {
            addCriterion("a_qid <", value, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidLessThanOrEqualTo(Integer value) {
            addCriterion("a_qid <=", value, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidIn(List<Integer> values) {
            addCriterion("a_qid in", values, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidNotIn(List<Integer> values) {
            addCriterion("a_qid not in", values, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidBetween(Integer value1, Integer value2) {
            addCriterion("a_qid between", value1, value2, "aQid");
            return (Criteria) this;
        }

        public Criteria andAQidNotBetween(Integer value1, Integer value2) {
            addCriterion("a_qid not between", value1, value2, "aQid");
            return (Criteria) this;
        }

        public Criteria andATimeIsNull() {
            addCriterion("a_Time is null");
            return (Criteria) this;
        }

        public Criteria andATimeIsNotNull() {
            addCriterion("a_Time is not null");
            return (Criteria) this;
        }

        public Criteria andATimeEqualTo(Date value) {
            addCriterion("a_Time =", value, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeNotEqualTo(Date value) {
            addCriterion("a_Time <>", value, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeGreaterThan(Date value) {
            addCriterion("a_Time >", value, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeGreaterThanOrEqualTo(Date value) {
            addCriterion("a_Time >=", value, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeLessThan(Date value) {
            addCriterion("a_Time <", value, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeLessThanOrEqualTo(Date value) {
            addCriterion("a_Time <=", value, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeIn(List<Date> values) {
            addCriterion("a_Time in", values, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeNotIn(List<Date> values) {
            addCriterion("a_Time not in", values, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeBetween(Date value1, Date value2) {
            addCriterion("a_Time between", value1, value2, "aTime");
            return (Criteria) this;
        }

        public Criteria andATimeNotBetween(Date value1, Date value2) {
            addCriterion("a_Time not between", value1, value2, "aTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 11 16:28:48 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answer
     *
     * @mbg.generated Thu Apr 11 16:28:48 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}