package com.xxpt.bean;

public class College {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.c_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.c_name
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String cName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.c_id
     *
     * @return the value of college.c_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.c_id
     *
     * @param cId the value for college.c_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.c_name
     *
     * @return the value of college.c_name
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.c_name
     *
     * @param cName the value for college.c_name
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }
}