package com.xxpt.bean;

public class College {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.c_id
     *
     * @mbg.generated Wed Apr 03 14:28:47 CST 2019
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.c_name
     *
     * @mbg.generated Wed Apr 03 14:28:47 CST 2019
     */
    private String cName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.c_id
     *
     * @return the value of college.c_id
     *
     * @mbg.generated Wed Apr 03 14:28:47 CST 2019
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.c_id
     *
     * @param cId the value for college.c_id
     *
     * @mbg.generated Wed Apr 03 14:28:47 CST 2019
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.c_name
     *
     * @return the value of college.c_name
     *
     * @mbg.generated Wed Apr 03 14:28:47 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.c_name
     *
     * @param cName the value for college.c_name
     *
     * @mbg.generated Wed Apr 03 14:28:47 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }
}