package com.xxpt.bean;

import java.util.Date;

public class Pdf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf.pdf_id
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    private Integer pdfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf.pdf_name
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    private String pdfName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf.pdf_path
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    private String pdfPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf.pdf_author
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    private String pdfAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf.pdf_time
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    private Date pdfTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf.pdf_id
     *
     * @return the value of pdf.pdf_id
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public Integer getPdfId() {
        return pdfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf.pdf_id
     *
     * @param pdfId the value for pdf.pdf_id
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public void setPdfId(Integer pdfId) {
        this.pdfId = pdfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf.pdf_name
     *
     * @return the value of pdf.pdf_name
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public String getPdfName() {
        return pdfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf.pdf_name
     *
     * @param pdfName the value for pdf.pdf_name
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public void setPdfName(String pdfName) {
        this.pdfName = pdfName == null ? null : pdfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf.pdf_path
     *
     * @return the value of pdf.pdf_path
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public String getPdfPath() {
        return pdfPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf.pdf_path
     *
     * @param pdfPath the value for pdf.pdf_path
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public void setPdfPath(String pdfPath) {
        this.pdfPath = pdfPath == null ? null : pdfPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf.pdf_author
     *
     * @return the value of pdf.pdf_author
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public String getPdfAuthor() {
        return pdfAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf.pdf_author
     *
     * @param pdfAuthor the value for pdf.pdf_author
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public void setPdfAuthor(String pdfAuthor) {
        this.pdfAuthor = pdfAuthor == null ? null : pdfAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf.pdf_time
     *
     * @return the value of pdf.pdf_time
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public Date getPdfTime() {
        return pdfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf.pdf_time
     *
     * @param pdfTime the value for pdf.pdf_time
     *
     * @mbg.generated Tue Apr 09 15:39:22 CST 2019
     */
    public void setPdfTime(Date pdfTime) {
        this.pdfTime = pdfTime;
    }

    @Override
    public String toString() {
        return "Pdf{" +
                "pdfId=" + pdfId +
                ", pdfName='" + pdfName + '\'' +
                ", pdfPath='" + pdfPath + '\'' +
                ", pdfAuthor='" + pdfAuthor + '\'' +
                ", pdfTime=" + pdfTime +
                '}';
    }
}