package com.xxpt.bean;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_password
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String sPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_college
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String sCollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_tid
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String sTid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_id
     *
     * @return the value of student.s_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_id
     *
     * @param sId the value for student.s_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_password
     *
     * @return the value of student.s_password
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String getsPassword() {
        return sPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_password
     *
     * @param sPassword the value for student.s_password
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void setsPassword(String sPassword) {
        this.sPassword = sPassword == null ? null : sPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param sName the value for student.s_name
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_college
     *
     * @return the value of student.s_college
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String getsCollege() {
        return sCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_college
     *
     * @param sCollege the value for student.s_college
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void setsCollege(String sCollege) {
        this.sCollege = sCollege == null ? null : sCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_tid
     *
     * @return the value of student.s_tid
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String getsTid() {
        return sTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_tid
     *
     * @param sTid the value for student.s_tid
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void setsTid(String sTid) {
        this.sTid = sTid == null ? null : sTid.trim();
    }
}