package com.xxpt.bean;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_password
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String tPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_hiredate
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    private String tHiredate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_id
     *
     * @return the value of teacher.t_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_id
     *
     * @param tId the value for teacher.t_id
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void settId(String tId) {
        this.tId = tId == null ? null : tId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_password
     *
     * @return the value of teacher.t_password
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String gettPassword() {
        return tPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_password
     *
     * @param tPassword the value for teacher.t_password
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void settPassword(String tPassword) {
        this.tPassword = tPassword == null ? null : tPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_hiredate
     *
     * @return the value of teacher.t_hiredate
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public String gettHiredate() {
        return tHiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_hiredate
     *
     * @param tHiredate the value for teacher.t_hiredate
     *
     * @mbg.generated Fri Mar 29 17:19:01 CST 2019
     */
    public void settHiredate(String tHiredate) {
        this.tHiredate = tHiredate == null ? null : tHiredate.trim();
    }
}