package com.xxpt.bean;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_id
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    private String tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_name
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_hiredate
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    private String tHiredate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_id
     *
     * @return the value of teacher.t_id
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_id
     *
     * @param tId the value for teacher.t_id
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    public void settId(String tId) {
        this.tId = tId == null ? null : tId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_name
     *
     * @return the value of teacher.t_name
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_name
     *
     * @param tName the value for teacher.t_name
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_hiredate
     *
     * @return the value of teacher.t_hiredate
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    public String gettHiredate() {
        return tHiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_hiredate
     *
     * @param tHiredate the value for teacher.t_hiredate
     *
     * @mbg.generated Wed Apr 03 14:29:16 CST 2019
     */
    public void settHiredate(String tHiredate) {
        this.tHiredate = tHiredate == null ? null : tHiredate.trim();
    }
}