package com.xxpt.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_level
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    private String uLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    private String uPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_level
     *
     * @return the value of user.u_level
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    public String getuLevel() {
        return uLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_level
     *
     * @param uLevel the value for user.u_level
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    public void setuLevel(String uLevel) {
        this.uLevel = uLevel == null ? null : uLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbg.generated Fri Mar 08 21:21:16 CST 2019
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

	public User() {
		super();
	}

	public User(String uId, String uLevel, String uPassword) {
		super();
		this.uId = uId;
		this.uLevel = uLevel;
		this.uPassword = uPassword;
	}

	@Override
	public String toString() {
		return "User [uId=" + uId + ", uLevel=" + uLevel + ", uPassword=" + uPassword + "]";
	}
}